name: home_services
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0 # Update to a compatible version
  firebase_auth: ^5.3.0  # Use the latest stable version
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.1
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  shared_preferences: ^2.0.9
  flutter_screenutil: ^5.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
